name: Auto Review

on:
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download bento
        run: |
          curl -sL https://github.com/catatsuy/bento/releases/latest/download/bento-linux-amd64.tar.gz | tar xz -C /tmp
          sudo mv /tmp/bento /usr/local/bin/

      - name: Run Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          REVIEW_CONTENT=$(git diff origin/main...HEAD | bento -review)
          echo "REVIEW_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$REVIEW_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Find Existing Comment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          comment_id=$(gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            --jq '.[] | select(.user.login == "github-actions[bot]") | select(.body | contains("Automatic Review")) | .id')
          if [ -n "$comment_id" ]; then
            echo "comment_id=$comment_id" >> $GITHUB_ENV
          fi

      - name: Post Review as a Comment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          REVIEW_BODY=$(printf "### Automatic Review\n\n%s" "${{ env.REVIEW_CONTENT }}")
          if [ -n "${{ env.comment_id }}" ]; then
            # Update existing comment
            gh api \
              -X PATCH \
              repos/${{ github.repository }}/issues/comments/${{ env.comment_id }} \
              -f body="${REVIEW_BODY}"
          else
            # Create a new comment
            gh api \
              -X POST \
              repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
              -f body="${REVIEW_BODY}"
          fi
